-- Seed editable Awakening Map hotspot/reference clusters from the curated in-repo taxonomy.
-- Safe to run repeatedly: rows are upserted by stable cluster ids.

insert into public.awakening_reference_clusters (
  id,
  group_id,
  label,
  summary,
  bounds,
  key_topics,
  keywords,
  matcher,
  related_cluster_ids,
  status
)
values
  (
    'great-awakening-core',
    'metaphysics',
    'Great Awakening Core',
    'Центральный нарратив карты: пробуждение, иллюзорность реальности и выбор оптимальной временной линии.',
    '{"height":0.18,"width":0.26,"x":0.34,"y":0.31}'::jsonb,
    '["Great Awakening","Everything is an illusion","Optimal Timeline Reality"]'::jsonb,
    '["great awakening","everything is an illusion","optimal timeline"]'::jsonb,
    '{"slugExact":["great-awakening","optimal-timeline-reality"],"titleIncludes":["great awakening","optimal timeline","everything is an illusion"]}'::jsonb,
    '["solar-flash","secret-space-program","qanon-earth-alliance"]'::jsonb,
    'published'
  ),
  (
    'ai-signal',
    'suppressed-science',
    'Artificial Intelligence Signal',
    'Древний A.I.-сигнал, рептилоиды и солнце собраны в одну техно-эсхатологическую угрозу.',
    '{"height":0.2,"width":0.25,"x":0.03,"y":0.04}'::jsonb,
    '["Ancient A.I.","Electric Sun","Reptilian infection","Solar purge"]'::jsonb,
    '["ai","artificial intelligence","reptilians","electric sun","the sun"]'::jsonb,
    '{"slugExact":["artificial-intelligence","electric-sun"],"titleIncludes":["artificial intelligence","electric sun","the sun","reptilian"]}'::jsonb,
    '["solar-flash","dark-fleet-saturn","healing-energy"]'::jsonb,
    'published'
  ),
  (
    'solar-flash',
    'metaphysics',
    'Great Solar Flash',
    'Центральная ось карты: солнечное событие должно запустить очищение, disclosure и сдвиг сознания.',
    '{"height":0.22,"width":0.27,"x":0.23,"y":0.11}'::jsonb,
    '["Great Solar Flash","Consciousness Renaissance","Collective Consciousness"]'::jsonb,
    '["great solar flash","consciousness renaissance","collective consciousness"]'::jsonb,
    '{"slugExact":["great-solar-flash","collective-consciousness"],"titleIncludes":["great solar flash","solar flash","collective consciousness"]}'::jsonb,
    '["rainbow-body","galactic-federation","secret-space-program"]'::jsonb,
    'published'
  ),
  (
    'rainbow-body',
    'spiritual-practice',
    'Rainbow Body & Meditation',
    'Буддийско-эзотерический блок про медитацию, ригпа, бардо и освобождение от цикла перерождений.',
    '{"height":0.22,"width":0.24,"x":0.54,"y":0.09}'::jsonb,
    '["Rainbow Body","Dzogchen","Bardo","Rigpa"]'::jsonb,
    '["rainbow body","dzogchen","bardo","meditation","rigpa"]'::jsonb,
    '{"slugExact":["rainbow-body","meditation"],"titleIncludes":["rainbow body","dzogchen","bardo","meditation","rigpa"]}'::jsonb,
    '["solar-flash","psychedelic-renaissance","lightworkers-ascension"]'::jsonb,
    'published'
  ),
  (
    'return-to-source',
    'spiritual-practice',
    'Return to Source',
    'Верхний правый блок описывает возвращение к Source, oneness и практики освобождения через медитацию.',
    '{"height":0.15,"width":0.18,"x":0.78,"y":0.04}'::jsonb,
    '["Return to Source","Oneness","Bardo","Meditation Rigpa"]'::jsonb,
    '["return to source","oneness","bardo","rigpa"]'::jsonb,
    '{"slugExact":["return-to-source","oneness"],"titleIncludes":["return to source","oneness","bardo","rigpa"]}'::jsonb,
    '["rainbow-body","solar-flash","lightworkers-ascension"]'::jsonb,
    'published'
  ),
  (
    'psychedelic-renaissance',
    'psychedelics',
    'Psychedelic Renaissance',
    'Психоделики показаны как интерфейс к многомерной реальности и ускоритель пробуждения.',
    '{"height":0.18,"width":0.24,"x":0.54,"y":0.26}'::jsonb,
    '["DMT","Psilocybin","Hyperspace","Terence McKenna"]'::jsonb,
    '["dmt","psilocybin","psychedelic renaissance","hyperspace","mckenna"]'::jsonb,
    '{"slugExact":["psychedelic-renaissance","dmt"],"titleIncludes":["psychedelic","psilocybin","dmt","hyperspace","terence mckenna"]}'::jsonb,
    '["rainbow-body","entheogens","lightworkers-ascension"]'::jsonb,
    'published'
  ),
  (
    'secret-space-program',
    'secret-space-program',
    'Secret Space Program',
    'Крупнейший техно-конспирологический кластер: тайные космические программы, технологии и информаторы.',
    '{"height":0.24,"width":0.31,"x":0.28,"y":0.3}'::jsonb,
    '["Solar Warden","USAP","MILAB","SSP Whistleblowers"]'::jsonb,
    '["ssp","secret space program","solar warden","milab","usap"]'::jsonb,
    '{"slugExact":["secret-space-program","solar-warden"],"titleIncludes":["secret space program","solar warden","milab","usap","whistleblower"]}'::jsonb,
    '["dark-fleet-saturn","moon-mars-venus","solar-flash"]'::jsonb,
    'published'
  ),
  (
    'super-federation',
    'galactic-federations',
    'Super Federation & Free Will',
    'Центрально-правый сектор про Super Federation, Law of One и идею свободной воли как космического закона.',
    '{"height":0.18,"width":0.25,"x":0.45,"y":0.46}'::jsonb,
    '["Super Federation","RA: Law of One","The Galactic Federation","Free Will"]'::jsonb,
    '["super federation","galactic federation","law of one","free will"]'::jsonb,
    '{"slugExact":["super-federation","free-will"],"titleIncludes":["super federation","galactic federation","law of one","free will"]}'::jsonb,
    '["galactic-federation","ancient-builder-race","great-awakening-core"]'::jsonb,
    'published'
  ),
  (
    'dark-fleet-saturn',
    'hidden-infrastructure',
    'Saturn, Draco & Dark Fleet',
    'Темная космическая иерархия вокруг Сатурна, Draco-альянса, Dark Fleet и внеземного рабства.',
    '{"height":0.19,"width":0.28,"x":0.03,"y":0.24}'::jsonb,
    '["Saturn","Dark Fleet","Draco alliance","Off-planet slave trade"]'::jsonb,
    '["saturn","dark fleet","draco","orion syndicate","slave trade"]'::jsonb,
    '{"slugExact":["saturn","dark-fleet"],"titleIncludes":["saturn","dark fleet","draco","orion syndicate","slave trade"]}'::jsonb,
    '["secret-space-program","moon-mars-venus","ai-signal"]'::jsonb,
    'published'
  ),
  (
    'qanon-earth-alliance',
    'earth-conspiracy',
    'QAnon & Earth Alliance',
    'Политическая ветка Great Awakening: QAnon, white hats, tribunals и борьба с cabal.',
    '{"height":0.18,"width":0.26,"x":0.05,"y":0.54}'::jsonb,
    '["QAnon","White Hats","Tribunals","Save the Children"]'::jsonb,
    '["qanon","earth alliance","white hats","tribunals","save the children"]'::jsonb,
    '{"slugExact":["qanon","earth-alliance"],"titleIncludes":["q anon","qanon","earth alliance","white hats","tribunals"]}'::jsonb,
    '["vatican-occult-control","healing-energy","secret-space-program"]'::jsonb,
    'published'
  ),
  (
    'cabal-deep-state',
    'earth-conspiracy',
    'Cabal, Deep State & Illuminati',
    'Нижний политический слой карты: cabal, deep state, Illuminati и земные структуры скрытого управления.',
    '{"height":0.15,"width":0.25,"x":0.04,"y":0.78}'::jsonb,
    '["Cabal","Deep State","Illuminati","Council of 200"]'::jsonb,
    '["cabal","deep state","illuminati","council of 200"]'::jsonb,
    '{"slugExact":["cabal","deep-state","illuminati"],"titleIncludes":["cabal","deep state","illuminati","council of 200"]}'::jsonb,
    '["qanon-earth-alliance","vatican-occult-control","secret-space-program"]'::jsonb,
    'published'
  ),
  (
    'healing-energy',
    'suppressed-science',
    'Healing & Free Energy',
    'Псевдонаучный healing-блок: free energy, Tesla-мифология, Rife, orgone и sound healing.',
    '{"height":0.15,"width":0.24,"x":0.16,"y":0.44}'::jsonb,
    '["Tesla","Rife","Orgone","Free Energy"]'::jsonb,
    '["tesla","rife","orgone","wireless energy","holistic healing"]'::jsonb,
    '{"slugExact":["nikola-tesla","free-energy"],"titleIncludes":["tesla","rife","orgone","free energy","holistic healing"]}'::jsonb,
    '["qanon-earth-alliance","ai-signal","solar-flash"]'::jsonb,
    'published'
  ),
  (
    'galactic-federation',
    'galactic-federations',
    'Galactic Federation & Law of One',
    'Космическо-духовный блок про Law of One, Blue Avians, Sphere Being Alliance и channeling.',
    '{"height":0.2,"width":0.31,"x":0.44,"y":0.37}'::jsonb,
    '["Law of One","Blue Avians","Sphere Being Alliance","Channeling"]'::jsonb,
    '["galactic federation","law of one","blue avians","sphere beings"]'::jsonb,
    '{"slugExact":["law-of-one","galactic-federation"],"titleIncludes":["galactic federation","law of one","blue avians","sphere being"]}'::jsonb,
    '["solar-flash","ancient-builder-race","lightworkers-ascension"]'::jsonb,
    'published'
  ),
  (
    'moon-mars-venus',
    'hidden-infrastructure',
    'Moon, Mars & Venus Infrastructure',
    'Луна, Марс и Венера показаны как обжитые и политически управляемые пространства с базами и руинами.',
    '{"height":0.19,"width":0.3,"x":0.6,"y":0.41}'::jsonb,
    '["Moon","Mars","Venus","LOC","Cydonia"]'::jsonb,
    '["moon","mars","venus","cydonia","loc"]'::jsonb,
    '{"slugExact":["moon","mars","venus","cydonia"],"titleIncludes":["moon","mars","venus","cydonia","lunar operations command"]}'::jsonb,
    '["secret-space-program","dark-fleet-saturn","ancient-builder-race"]'::jsonb,
    'published'
  ),
  (
    'ancient-aliens',
    'ancient-civilizations',
    'Ancient Aliens & Alternative Archaeology',
    'Мегалиты, пирамиды, круги на полях и ancient aliens собраны как доказательная база lost history.',
    '{"height":0.2,"width":0.29,"x":0.24,"y":0.59}'::jsonb,
    '["Giza","Gobekli Tepe","Crop Circles","Montauk"]'::jsonb,
    '["ancient aliens","giza","gobekli tepe","crop circles","montauk"]'::jsonb,
    '{"slugExact":["ancient-aliens","giza-complex","gobekli-tepe"],"titleIncludes":["ancient aliens","giza","gobekli","crop circles","montauk"]}'::jsonb,
    '["ancient-builder-race","antarctica-inner-earth","qanon-earth-alliance"]'::jsonb,
    'published'
  ),
  (
    'lightworkers-ascension',
    'spiritual-practice',
    'Lightworkers & Ascension',
    'New Age-контур вокруг lightworkers, starseeds, higher mind, akashic records и ascension.',
    '{"height":0.17,"width":0.28,"x":0.53,"y":0.59}'::jsonb,
    '["Lightworkers","Starseeds","Akashic Records","Higher Mind"]'::jsonb,
    '["lightworkers","starseeds","indigos","higher mind","akashic records"]'::jsonb,
    '{"slugExact":["lightworkers","akashic-records"],"titleIncludes":["lightworkers","starseeds","indigos","higher mind","akashic"]}'::jsonb,
    '["rainbow-body","galactic-federation","entheogens"]'::jsonb,
    'published'
  ),
  (
    'vatican-occult-control',
    'earth-conspiracy',
    'Vatican & Occult Control',
    'Ватикан, иезуиты, оккультная власть и финансово-религиозный контроль связаны в единый вражеский узел.',
    '{"height":0.16,"width":0.25,"x":0.54,"y":0.74}'::jsonb,
    '["Vatican","Jesuits","Khazars","Project Paperclip"]'::jsonb,
    '["vatican","jesuits","khazars","lucifer telescope","project paperclip"]'::jsonb,
    '{"slugExact":["vatican","project-paperclip"],"titleIncludes":["vatican","jesuit","khazar","lucifer","paperclip"]}'::jsonb,
    '["qanon-earth-alliance","antarctica-inner-earth","moon-mars-venus"]'::jsonb,
    'published'
  ),
  (
    'antarctica-inner-earth',
    'hidden-infrastructure',
    'Antarctica & Inner Earth',
    'Антарктида, подземные и подводные базы, crashed craft и hidden civilization-инфраструктура.',
    '{"height":0.19,"width":0.24,"x":0.33,"y":0.71}'::jsonb,
    '["Antarctica","Inner Earth","Dulce","Area 51"]'::jsonb,
    '["antarctica","inner earth","dulce","area 51","undersea bases"]'::jsonb,
    '{"slugExact":["antarctica","inner-earth"],"titleIncludes":["antarctica","inner earth","area 51","dulce","undersea bases"]}'::jsonb,
    '["ancient-aliens","vatican-occult-control","moon-mars-venus"]'::jsonb,
    'published'
  ),
  (
    'inner-earth-civilizations',
    'hidden-infrastructure',
    'Inner Earth Civilizations',
    'Нижний сектор про внутреннюю Землю, Agartha, D.U.M.B.S и подземные базы как скрытую цивилизационную сеть.',
    '{"height":0.16,"width":0.27,"x":0.25,"y":0.8}'::jsonb,
    '["Inner Earth Civilizations","Agartha","D.U.M.B.S","Dulce"]'::jsonb,
    '["inner earth civilizations","agartha","dumbs","dulce"]'::jsonb,
    '{"slugExact":["inner-earth-civilizations","agartha","dulce"],"titleIncludes":["inner earth","agartha","d.u.m.b","dulce"]}'::jsonb,
    '["antarctica-inner-earth","ancient-aliens","dark-fleet-saturn"]'::jsonb,
    'published'
  ),
  (
    'entheogens',
    'psychedelics',
    'Entheogens & Shamans',
    'Шаманизм и энтеогены поданы как древний путь доступа к тем же многомерным истинам.',
    '{"height":0.14,"width":0.19,"x":0.69,"y":0.66}'::jsonb,
    '["Ayahuasca","Shamans","LSD","DMT"]'::jsonb,
    '["entheogens","ayahuasca","lsd","shamans","dmt"]'::jsonb,
    '{"slugExact":["entheogens","ayahuasca"],"titleIncludes":["entheogen","ayahuasca","lsd","shaman","dmt"]}'::jsonb,
    '["psychedelic-renaissance","lightworkers-ascension","rainbow-body"]'::jsonb,
    'published'
  ),
  (
    'crystals-cymatics',
    'suppressed-science',
    'Crystals, Cymatics & Energy Body',
    'Правый нижний energy-body блок: crystals, cymatics, chakras и merkaba как язык тонких практик.',
    '{"height":0.16,"width":0.21,"x":0.75,"y":0.58}'::jsonb,
    '["Crystals","Cymatics","Chakras","Merkaba"]'::jsonb,
    '["crystals","cymatics","chakras","merkaba"]'::jsonb,
    '{"slugExact":["crystals","cymatics","chakras","merkaba"],"titleIncludes":["crystals","cymatics","chakras","merkaba"]}'::jsonb,
    '["healing-energy","lightworkers-ascension","entheogens"]'::jsonb,
    'published'
  ),
  (
    'ancient-builder-race',
    'ancient-civilizations',
    'Ancient Builder Race',
    'Древняя сверхцивилизация объясняет руины по Солнечной системе, Maldek, Mars War и lost tech.',
    '{"height":0.17,"width":0.22,"x":0.44,"y":0.2}'::jsonb,
    '["Ancient Builder Race","Maldek","Mars War","Atlantis"]'::jsonb,
    '["ancient builder race","maldek","atlantis","pyramids","mars war"]'::jsonb,
    '{"slugExact":["ancient-builder-race","maldek"],"titleIncludes":["ancient builder race","maldek","atlantis","mars war"]}'::jsonb,
    '["ancient-aliens","moon-mars-venus","galactic-federation"]'::jsonb,
    'published'
  )
on conflict (id) do update
set
  group_id = excluded.group_id,
  label = excluded.label,
  summary = excluded.summary,
  bounds = excluded.bounds,
  key_topics = excluded.key_topics,
  keywords = excluded.keywords,
  matcher = excluded.matcher,
  related_cluster_ids = excluded.related_cluster_ids,
  status = excluded.status,
  updated_at = now();
