-- Minimal Awakening Map seed for staging/demo environments.
-- Safe to run repeatedly: rows are upserted by stable Brain node ids.

with upserted_nodes as (
  insert into public.node_projection (
    id,
    brain_node_id,
    node_type,
    slug,
    title,
    summary,
    content,
    status,
    credibility,
    claim_status,
    source_refs,
    published_at,
    is_stale
  )
  values
    (
      '10000000-0000-4000-8000-000000000001',
      'seed:topic:awakening-map',
      'topic',
      'awakening-map',
      'Карта пробуждения',
      'Опорная тема для интерактивной карты: показывает связи, источники и открытые хвосты.',
      jsonb_build_object(
        'facts',
        jsonb_build_array(
          jsonb_build_object(
            'text',
            'Карта должна показывать не готовые ответы, а проверяемые связи между темами, источниками и спорными утверждениями.',
            'source_refs',
            jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map'))
          )
        ),
        'related_node_refs',
        jsonb_build_array(
          jsonb_build_object('nodeId', 'seed:claim:source-first', 'relation', 'expands', 'reason', 'Метод чтения карты'),
          jsonb_build_object('nodeId', 'seed:source:tz-map', 'relation', 'supported_by', 'reason', 'ТЗ и исходный плакат')
        )
      ),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000002',
      'seed:claim:source-first',
      'claim',
      null,
      'Source-first проверка',
      'Каждая публичная карточка и связь должны иметь источник или явный unresolved-хвост.',
      jsonb_build_object(
        'versions',
        jsonb_build_array(
          jsonb_build_object('text', 'Без источников карточка не должна выглядеть как доказанный факт.')
        ),
        'related_node_refs',
        jsonb_build_array(
          jsonb_build_object('nodeId', 'seed:source:tz-map', 'relation', 'supported_by')
        )
      ),
      'published',
      null,
      'supported',
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000003',
      'seed:source:tz-map',
      'source',
      'interactive-map-brief',
      'ТЗ интерактивной карты',
      'Техническое задание и визуальный референс для первого публичного слоя карты.',
      jsonb_build_object(
        'source_type',
        'brief',
        'notes',
        jsonb_build_array('Seed source for validating the public map and dossier UI.')
      ),
      'published',
      'B',
      null,
      '[]'::jsonb,
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000004',
      'seed:document:poster',
      'document',
      null,
      'Оригинальная карта Great Awakening',
      'Визуальный референс с темами, кластерами и плотной сетью ассоциаций.',
      jsonb_build_object(
        'related_node_refs',
        jsonb_build_array(
          jsonb_build_object('nodeId', 'seed:topic:awakening-map', 'relation', 'derived_from')
        )
      ),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000005',
      'seed:topic:great-awakening',
      'topic',
      'great-awakening',
      'Great Awakening',
      'Центральная тема карты: пробуждение, иллюзорность реальности и переход к оптимальной временной линии.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:great-solar-flash', 'relation', 'expands'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000006',
      'seed:topic:great-solar-flash',
      'topic',
      'great-solar-flash',
      'Great Solar Flash',
      'Верхний центральный сектор про солнечное событие, collective consciousness и spiritual body ascension.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:rainbow-body', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000007',
      'seed:topic:return-to-source',
      'topic',
      'return-to-source',
      'Return to Source',
      'Правая верхняя зона про Source, oneness, bardo, rigpa и медитативное освобождение.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:rainbow-body', 'relation', 'belongs_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000008',
      'seed:topic:rainbow-body',
      'topic',
      'rainbow-body',
      'Rainbow Body & Meditation',
      'Кластер Tibetan Buddhism, Dzogchen, Bardo, Rigpa и практик освобождения.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:psychedelic-renaissance', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000009',
      'seed:topic:psychedelic-renaissance',
      'topic',
      'psychedelic-renaissance',
      'Psychedelic Renaissance',
      'Сектор DMT, psilocybin, hyperspace и Terence McKenna как altered states-ветка карты.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:dmt', 'relation', 'expands'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000010',
      'seed:topic:dmt',
      'topic',
      'dmt',
      'DMT',
      'Тема из psychedelic-блока карты, связанная с hyperspace и McKenna-нарративом.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:entheogens', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000011',
      'seed:topic:secret-space-program',
      'topic',
      'secret-space-program',
      'Secret Space Program',
      'Центральный техно-конспирологический кластер про SSP, USAP, MILAB и whistleblowers.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:solar-warden', 'relation', 'expands'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000012',
      'seed:topic:solar-warden',
      'topic',
      'solar-warden',
      'Solar Warden',
      'Подтема SSP на карте, связанная с U.S. Navy space fleet и secret space disclosures.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:moon', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000013',
      'seed:topic:dark-fleet',
      'topic',
      'dark-fleet',
      'Dark Fleet',
      'Левый сектор карты про Saturn, Draco alliance, Orion Syndicate и off-planet slave trade.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:secret-space-program', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000014',
      'seed:topic:qanon',
      'topic',
      'qanon',
      'QAnon & Earth Alliance',
      'Нижняя левая политическая ветка карты: QAnon, white hats, tribunals и save the children.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:cabal', 'relation', 'contradicts'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000015',
      'seed:topic:cabal',
      'topic',
      'cabal',
      'Cabal, Deep State & Illuminati',
      'Нижний политический слой карты про cabal, deep state, Illuminati и Council of 200.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:vatican', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000016',
      'seed:topic:free-energy',
      'topic',
      'free-energy',
      'Healing & Free Energy',
      'Сектор Tesla, Rife, orgone, sound healing и suppressed science/free energy.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:crystals', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000017',
      'seed:topic:galactic-federation',
      'topic',
      'galactic-federation',
      'Galactic Federation & Law of One',
      'Правый центральный кластер про Galactic Federation, Law of One, Blue Avians и channeling.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:law-of-one', 'relation', 'expands'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000018',
      'seed:topic:law-of-one',
      'topic',
      'law-of-one',
      'Law of One',
      'Подтема galactic-федеративного блока, связанная с RA и channeling-структурой карты.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:super-federation', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000019',
      'seed:topic:super-federation',
      'topic',
      'super-federation',
      'Super Federation & Free Will',
      'Сектор Super Federation, RA: Law of One, Galactic Federation и темы free will.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:ancient-builder-race', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000020',
      'seed:topic:moon',
      'topic',
      'moon',
      'Moon, Mars & Venus Infrastructure',
      'Правый сектор карты про Moon, Mars, Venus, LOC, Cydonia и внеземные базы.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:mars', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000021',
      'seed:topic:mars',
      'topic',
      'mars',
      'Mars & Cydonia',
      'Подтема planetary infrastructure-кластера про Mars, Cydonia и ancient ruins.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:ancient-builder-race', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000022',
      'seed:topic:ancient-aliens',
      'topic',
      'ancient-aliens',
      'Ancient Aliens & Alternative Archaeology',
      'Нижний центральный сектор про Giza, Gobekli Tepe, crop circles и alternative archaeology.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:ancient-builder-race', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000023',
      'seed:topic:ancient-builder-race',
      'topic',
      'ancient-builder-race',
      'Ancient Builder Race',
      'Центрально-правый древний кластер про Ancient Builder Race, Maldek, Atlantis и Mars War.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:ancient-aliens', 'relation', 'expands'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000024',
      'seed:topic:antarctica',
      'topic',
      'antarctica',
      'Antarctica & Inner Earth',
      'Нижний сектор карты про Antarctica, Inner Earth, Area 51, Dulce и hidden infrastructure.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:inner-earth-civilizations', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000025',
      'seed:topic:inner-earth-civilizations',
      'topic',
      'inner-earth-civilizations',
      'Inner Earth Civilizations',
      'Нижняя зона про Inner Earth civilizations, Agartha, D.U.M.B.S и подземные базы.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:antarctica', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000026',
      'seed:topic:crystals',
      'topic',
      'crystals',
      'Crystals, Chakras & Merkaba',
      'Правый нижний energy-body сектор карты про crystals, chakras, merkaba и subtle body practices.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:cymatics', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000027',
      'seed:topic:cymatics',
      'topic',
      'cymatics',
      'Cymatics',
      'Подтема crystals/energy-body сектора про sound, vibration и геометрию формы.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:free-energy', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    ),
    (
      '10000000-0000-4000-8000-000000000028',
      'seed:topic:vatican',
      'topic',
      'vatican',
      'Vatican & Occult Control',
      'Нижний правый сектор карты про Vatican, Jesuits, Khazars, L.U.C.I.F.E.R. telescope и occult control.',
      jsonb_build_object('related_node_refs', jsonb_build_array(jsonb_build_object('nodeId', 'seed:topic:cabal', 'relation', 'related_to'))),
      'published',
      null,
      null,
      jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
      now(),
      false
    )
  on conflict (brain_node_id) do update
  set
    node_type = excluded.node_type,
    slug = excluded.slug,
    title = excluded.title,
    summary = excluded.summary,
    content = excluded.content,
    status = excluded.status,
    credibility = excluded.credibility,
    claim_status = excluded.claim_status,
    source_refs = excluded.source_refs,
    published_at = coalesce(public.node_projection.published_at, excluded.published_at),
    is_stale = false,
    updated_at = now()
  returning id, brain_node_id
)
insert into public.graph_edges (
  id,
  from_node_id,
  to_node_id,
  relation_type,
  strength,
  source_refs,
  status
)
values
  (
    '20000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000001',
    '10000000-0000-4000-8000-000000000002',
    'expands',
    0.86,
    jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
    'published'
  ),
  (
    '20000000-0000-4000-8000-000000000002',
    '10000000-0000-4000-8000-000000000002',
    '10000000-0000-4000-8000-000000000003',
    'supported_by',
    0.94,
    jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
    'published'
  ),
  (
    '20000000-0000-4000-8000-000000000003',
    '10000000-0000-4000-8000-000000000004',
    '10000000-0000-4000-8000-000000000001',
    'derived_from',
    0.72,
    jsonb_build_array(jsonb_build_object('nodeId', 'seed:source:tz-map', 'title', 'ТЗ интерактивной карты')),
    'published'
  )
on conflict (id) do update
set
  from_node_id = excluded.from_node_id,
  to_node_id = excluded.to_node_id,
  relation_type = excluded.relation_type,
  strength = excluded.strength,
  source_refs = excluded.source_refs,
  status = excluded.status,
  updated_at = now();
